/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { JobOfferResponseDto } from '../../models/job-offer-response-dto';

export interface GetJobOfferById$Params {
  id: number;
}

export function getJobOfferById(http: HttpClient, rootUrl: string, params: GetJobOfferById$Params, context?: HttpContext): Observable<StrictHttpResponse<JobOfferResponseDto>> {
  const rb = new RequestBuilder(rootUrl, getJobOfferById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<JobOfferResponseDto>;
    })
  );
}

getJobOfferById.PATH = '/rh/job-offers/{id}';
