/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { JobOfferResponseDto } from '../../models/job-offer-response-dto';
import { UpdateJobOfferDto } from '../../models/update-job-offer-dto';

export interface UpdateJobOffer$Params {
  id: number;
      body: UpdateJobOfferDto
}

export function updateJobOffer(http: HttpClient, rootUrl: string, params: UpdateJobOffer$Params, context?: HttpContext): Observable<StrictHttpResponse<JobOfferResponseDto>> {
  const rb = new RequestBuilder(rootUrl, updateJobOffer.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<JobOfferResponseDto>;
    })
  );
}

updateJobOffer.PATH = '/rh/update-job-offers/{id}';
