/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApplicationListDto } from '../../models/application-list-dto';

export interface GetApplicationsByJobOffer$Params {
  jobOfferId: number;
  status?: 'DRAFT' | 'SUBMITTED' | 'UNDER_REVIEW' | 'AI_SCORED' | 'SHORTLISTED' | 'INTERVIEW_SCHEDULED' | 'INTERVIEW_COMPLETED' | 'ACCEPTED' | 'REJECTED' | 'WITHDRAWN';
}

export function getApplicationsByJobOffer(http: HttpClient, rootUrl: string, params: GetApplicationsByJobOffer$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ApplicationListDto>>> {
  const rb = new RequestBuilder(rootUrl, getApplicationsByJobOffer.PATH, 'get');
  if (params) {
    rb.path('jobOfferId', params.jobOfferId, {});
    rb.query('status', params.status, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ApplicationListDto>>;
    })
  );
}

getApplicationsByJobOffer.PATH = '/rh/applications/job-offer/{jobOfferId}';
