/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApplicationDetailDto } from '../../models/application-detail-dto';
import { UpdateApplicationStatusDto } from '../../models/update-application-status-dto';

export interface UpdateApplicationStatus$Params {
  applicationId: number;
      body: UpdateApplicationStatusDto
}

export function updateApplicationStatus(http: HttpClient, rootUrl: string, params: UpdateApplicationStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<ApplicationDetailDto>> {
  const rb = new RequestBuilder(rootUrl, updateApplicationStatus.PATH, 'put');
  if (params) {
    rb.path('applicationId', params.applicationId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApplicationDetailDto>;
    })
  );
}

updateApplicationStatus.PATH = '/rh/applications/{applicationId}/status';
