/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApplicationStatsDto } from '../../models/application-stats-dto';

export interface GetApplicationStats$Params {
  jobOfferId: number;
}

export function getApplicationStats(http: HttpClient, rootUrl: string, params: GetApplicationStats$Params, context?: HttpContext): Observable<StrictHttpResponse<ApplicationStatsDto>> {
  const rb = new RequestBuilder(rootUrl, getApplicationStats.PATH, 'get');
  if (params) {
    rb.path('jobOfferId', params.jobOfferId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApplicationStatsDto>;
    })
  );
}

getApplicationStats.PATH = '/rh/applications/job-offer/{jobOfferId}/stats';
