/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApplicationDetailDto } from '../../models/application-detail-dto';

export interface RejectApplication$Params {
  applicationId: number;
}

export function rejectApplication(http: HttpClient, rootUrl: string, params: RejectApplication$Params, context?: HttpContext): Observable<StrictHttpResponse<ApplicationDetailDto>> {
  const rb = new RequestBuilder(rootUrl, rejectApplication.PATH, 'put');
  if (params) {
    rb.path('applicationId', params.applicationId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApplicationDetailDto>;
    })
  );
}

rejectApplication.PATH = '/rh/applications/{applicationId}/reject';
