/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApplicationDetailDto } from '../../models/application-detail-dto';
import { ShortlistApplicationsDto } from '../../models/shortlist-applications-dto';

export interface ShortlistApplications$Params {
  jobOfferId: number;
      body: ShortlistApplicationsDto
}

export function shortlistApplications(http: HttpClient, rootUrl: string, params: ShortlistApplications$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ApplicationDetailDto>>> {
  const rb = new RequestBuilder(rootUrl, shortlistApplications.PATH, 'post');
  if (params) {
    rb.path('jobOfferId', params.jobOfferId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ApplicationDetailDto>>;
    })
  );
}

shortlistApplications.PATH = '/rh/applications/job-offer/{jobOfferId}/shortlist';
