/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PublicJobOfferListDto } from '../../models/public-job-offer-list-dto';

export interface SearchJobOffers$Params {
  keyword: string;
}

export function searchJobOffers(http: HttpClient, rootUrl: string, params: SearchJobOffers$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PublicJobOfferListDto>>> {
  const rb = new RequestBuilder(rootUrl, searchJobOffers.PATH, 'get');
  if (params) {
    rb.query('keyword', params.keyword, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PublicJobOfferListDto>>;
    })
  );
}

searchJobOffers.PATH = '/candidate/job-offers/search';
