/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApplicationSubmissionResponseDto } from '../../models/application-submission-response-dto';

export interface SubmitApplication$Params {
  jobOfferId: number;
  firstName: string;
  lastName: string;
  email: string;
  phoneNumber?: string;
  address?: string;
  nationality?: string;
  highestDegree: string;
  majorField: string;
  educationalInstitution?: string;
  yearOfGraduation?: string;
  motivationEcole?: string;
  motivationPosition?: string;
  availableImmediately?: boolean;
  certifyAccurate?: boolean;
  consentGDPR?: boolean;
  electronicSignature?: string;
      body?: {
'cv'?: Blob;
}
}

export function submitApplication(http: HttpClient, rootUrl: string, params: SubmitApplication$Params, context?: HttpContext): Observable<StrictHttpResponse<ApplicationSubmissionResponseDto>> {
  const rb = new RequestBuilder(rootUrl, submitApplication.PATH, 'post');
  if (params) {
    rb.path('jobOfferId', params.jobOfferId, {});
    rb.query('firstName', params.firstName, {});
    rb.query('lastName', params.lastName, {});
    rb.query('email', params.email, {});
    rb.query('phoneNumber', params.phoneNumber, {});
    rb.query('address', params.address, {});
    rb.query('nationality', params.nationality, {});
    rb.query('highestDegree', params.highestDegree, {});
    rb.query('majorField', params.majorField, {});
    rb.query('educationalInstitution', params.educationalInstitution, {});
    rb.query('yearOfGraduation', params.yearOfGraduation, {});
    rb.query('motivationEcole', params.motivationEcole, {});
    rb.query('motivationPosition', params.motivationPosition, {});
    rb.query('availableImmediately', params.availableImmediately, {});
    rb.query('certifyAccurate', params.certifyAccurate, {});
    rb.query('consentGDPR', params.consentGDPR, {});
    rb.query('electronicSignature', params.electronicSignature, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApplicationSubmissionResponseDto>;
    })
  );
}

submitApplication.PATH = '/candidate/job-offers/{jobOfferId}/apply';
