/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApplicationSubmissionResponseDto {
  candidateName?: string;
  id?: number;
  jobOfferId?: number;
  jobOfferTitle?: string;
  message?: string;
  status?: string;
  submitDate?: string;
}
