/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CommissionApplicationListDto {
  alreadyEvaluatedByMe?: boolean;
  averageCommissionScore?: number;
  candidateEmail?: string;
  candidateName?: string;
  cvUrl?: string;
  evaluationCount?: number;
  highestDegree?: string;
  id?: number;
  scoreIA?: number;
  specialization?: string;
  submitDate?: string;
}
