/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EvaluationAverageDto } from '../models/evaluation-average-dto';
import { EvaluationResponseDto } from '../models/evaluation-response-dto';
export interface CommissionApplicationDetailDto {
  address?: string;
  alreadyEvaluatedByMe?: boolean;
  averageScores?: EvaluationAverageDto;
  cvUrl?: string;
  email?: string;
  evaluationCount?: number;
  evaluations?: Array<EvaluationResponseDto>;
  firstName?: string;
  highestDegree?: string;
  id?: number;
  jobOfferId?: number;
  jobOfferTitle?: string;
  justificationIA?: string;
  lastName?: string;
  matchingCompetences?: number;
  matchingDiploma?: number;
  matchingExperience?: number;
  scoreIA?: number;
  specialization?: string;
  submitDate?: string;
}
