/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CommissionActivityDto } from '../models/commission-activity-dto';
export interface CommissionStatsDto {
  activeCommissions?: number;
  averageMembersPerCommission?: number;
  evaluationCompletionRate?: number;
  mostActiveCommission?: CommissionActivityDto;
  totalCommissionMembers?: number;
  totalCommissions?: number;
  totalEvaluations?: number;
}
