/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CommissionMemberRequest {
  email?: string;
  expertiseArea?: string;
  firstName: string;
  lastName: string;
  password: string;
  phoneNumber?: string;
}
