/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CommissionActivityDto {
  candidatesCount?: number;
  commissionId?: number;
  commissionName?: string;
  completionRate?: number;
  evaluationsCount?: number;
  jobOfferTitle?: string;
  membersCount?: number;
}
