/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CommissionMemberResponseDto {
  expertiseArea?: string;
  id?: number;
  role?: string;
  userEmail?: string;
  userId?: number;
  userName?: string;
}
