/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CommissionMemberResponseDto } from '../models/commission-member-response-dto';
export interface CommissionResponseDto {
  createdAt?: string;
  createdById?: number;
  createdByName?: string;
  description?: string;
  id?: number;
  jobOfferId?: number;
  jobOfferTitle?: string;
  memberCount?: number;
  members?: Array<CommissionMemberResponseDto>;
  name?: string;
  president?: CommissionMemberResponseDto;
  status?: 'ACTIVE' | 'CLOSED' | 'ARCHIVED';
  updatedAt?: string;
}
