/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CommissionListDto {
  createdAt?: string;
  id?: number;
  jobOfferId?: number;
  jobOfferTitle?: string;
  memberCount?: number;
  name?: string;
  presidentName?: string;
  status?: 'ACTIVE' | 'CLOSED' | 'ARCHIVED';
}
