/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DashboardAlertDto {
  actionUrl?: string;
  alertType?: string;
  count?: number;
  message?: string;
  title?: string;
}
