/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DashboardOverviewDto {
  candidatesAccepted?: number;
  candidatesInterviewed?: number;
  candidatesShortlisted?: number;
  pendingEvaluations?: number;
  totalActiveJobOffers?: number;
  totalApplications?: number;
  totalCandidates?: number;
  totalCommissions?: number;
}
