/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface JobOfferResponseDto {
  applicationCount?: number;
  createdById?: number;
  createdByName?: string;
  dateLimite?: string;
  datePublication?: string;
  description?: string;
  experienceMin?: number;
  id?: number;
  jobStatus?: 'DRAFT' | 'PUBLISHED' | 'SUSPENDED' | 'ARCHIVED';
  jobTitle?: string;
  jobType?: 'PER' | 'PATS' | 'CONTRACTUEL';
  lastModifiedDate?: string;
  niveauEtudeRequis?: string;
  requiredSkills?: string;
  typeContrat?: 'CDD' | 'CDI' | 'STAGE';
}
