/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface JobOfferApplicationCountDto {
  applicationCount?: number;
  jobOfferId?: number;
  jobTitle?: string;
  shortlistedCount?: number;
  status?: string;
}
