/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MemberCommissionDto {
  commissionId?: number;
  commissionName?: string;
  jobOfferTitle?: string;
  myEvaluationsCount?: number;
  myRole?: string;
  shortlistedCandidatesCount?: number;
}
