/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { IaScoringResultDto } from '../models/ia-scoring-result-dto';
export interface ProcessCvResponseDto {
  application_id?: number;
  error_message?: string;
  scoring_result?: IaScoringResultDto;
  success?: boolean;
  total_processing_time?: number;
}
