/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PublicJobOfferDetailDto {
  applicationCount?: number;
  companyName?: string;
  dateLimite?: string;
  datePublication?: string;
  description?: string;
  experienceMin?: number;
  id?: number;
  jobTitle?: string;
  jobType?: 'PER' | 'PATS' | 'CONTRACTUEL';
  niveauEtudeRequis?: string;
  requiredSkills?: string;
  typeContrat?: 'CDD' | 'CDI' | 'STAGE';
}
