/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RecentActivityDto {
  activityType?: string;
  description?: string;
  entityId?: number;
  relatedEntity?: string;
  timestamp?: string;
}
