/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RhRequest {
  department?: string;
  email?: string;
  firstName: string;
  lastName: string;
  password: string;
  phoneNumber?: string;
  positionTitle?: string;
}
