/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TopJobOfferDto {
  averageIAScore?: number;
  daysActive?: number;
  jobOfferId?: number;
  jobTitle?: string;
  shortlistedCount?: number;
  status?: string;
  totalApplications?: number;
}
