/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateJobOfferDto {
  dateLimite?: string;
  description?: string;
  experienceMin?: number;
  jobStatus?: 'DRAFT' | 'PUBLISHED' | 'SUSPENDED' | 'ARCHIVED';
  jobTitle?: string;
  jobType?: 'PER' | 'PATS' | 'CONTRACTUEL';
  niveauEtudeRequis?: string;
  requiredSkills?: string;
  typeContrat?: 'CDD' | 'CDI' | 'STAGE';
}
