/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateCommissionDto {
  description?: string;
  name?: string;
  status?: 'ACTIVE' | 'CLOSED' | 'ARCHIVED';
}
