/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CommissionApplicationDetailDto } from '../../models/commission-application-detail-dto';

export interface GetApplicationDetails1$Params {
  commissionId: number;
  applicationId: number;
}

export function getApplicationDetails1(http: HttpClient, rootUrl: string, params: GetApplicationDetails1$Params, context?: HttpContext): Observable<StrictHttpResponse<CommissionApplicationDetailDto>> {
  const rb = new RequestBuilder(rootUrl, getApplicationDetails1.PATH, 'get');
  if (params) {
    rb.path('commissionId', params.commissionId, {});
    rb.path('applicationId', params.applicationId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CommissionApplicationDetailDto>;
    })
  );
}

getApplicationDetails1.PATH = '/commission-member/commissions/{commissionId}/applications/{applicationId}';
