/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateEvaluationDto } from '../../models/create-evaluation-dto';
import { EvaluationResponseDto } from '../../models/evaluation-response-dto';

export interface EvaluateApplication$Params {
  commissionId: number;
  applicationId: number;
      body: CreateEvaluationDto
}

export function evaluateApplication(http: HttpClient, rootUrl: string, params: EvaluateApplication$Params, context?: HttpContext): Observable<StrictHttpResponse<EvaluationResponseDto>> {
  const rb = new RequestBuilder(rootUrl, evaluateApplication.PATH, 'post');
  if (params) {
    rb.path('commissionId', params.commissionId, {});
    rb.path('applicationId', params.applicationId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EvaluationResponseDto>;
    })
  );
}

evaluateApplication.PATH = '/commission-member/commissions/{commissionId}/applications/{applicationId}/evaluate';
