/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CommissionApplicationListDto } from '../../models/commission-application-list-dto';

export interface GetShortlistedApplications1$Params {
  commissionId: number;
}

export function getShortlistedApplications1(http: HttpClient, rootUrl: string, params: GetShortlistedApplications1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CommissionApplicationListDto>>> {
  const rb = new RequestBuilder(rootUrl, getShortlistedApplications1.PATH, 'get');
  if (params) {
    rb.path('commissionId', params.commissionId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CommissionApplicationListDto>>;
    })
  );
}

getShortlistedApplications1.PATH = '/commission-member/commissions/{commissionId}/applications';
