/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MemberCommissionDto } from '../../models/member-commission-dto';

export interface GetMyCommissions$Params {
}

export function getMyCommissions(http: HttpClient, rootUrl: string, params?: GetMyCommissions$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MemberCommissionDto>>> {
  const rb = new RequestBuilder(rootUrl, getMyCommissions.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<MemberCommissionDto>>;
    })
  );
}

getMyCommissions.PATH = '/commission-member/my-commissions';
