/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CommissionResponseDto } from '../../models/commission-response-dto';

export interface GetCommissionById$Params {
  commissionId: number;
}

export function getCommissionById(http: HttpClient, rootUrl: string, params: GetCommissionById$Params, context?: HttpContext): Observable<StrictHttpResponse<CommissionResponseDto>> {
  const rb = new RequestBuilder(rootUrl, getCommissionById.PATH, 'get');
  if (params) {
    rb.path('commissionId', params.commissionId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CommissionResponseDto>;
    })
  );
}

getCommissionById.PATH = '/rh/commissions/{commissionId}';
