/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CommissionResponseDto } from '../../models/commission-response-dto';
import { UpdateCommissionDto } from '../../models/update-commission-dto';

export interface UpdateCommission$Params {
  commissionId: number;
      body: UpdateCommissionDto
}

export function updateCommission(http: HttpClient, rootUrl: string, params: UpdateCommission$Params, context?: HttpContext): Observable<StrictHttpResponse<CommissionResponseDto>> {
  const rb = new RequestBuilder(rootUrl, updateCommission.PATH, 'put');
  if (params) {
    rb.path('commissionId', params.commissionId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CommissionResponseDto>;
    })
  );
}

updateCommission.PATH = '/rh/commissions/{commissionId}';
