/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { JobOfferListDto } from '../../models/job-offer-list-dto';

export interface GetAllJobOffers$Params {
  status?: 'DRAFT' | 'PUBLISHED' | 'SUSPENDED' | 'ARCHIVED';
}

export function getAllJobOffers(http: HttpClient, rootUrl: string, params?: GetAllJobOffers$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<JobOfferListDto>>> {
  const rb = new RequestBuilder(rootUrl, getAllJobOffers.PATH, 'get');
  if (params) {
    rb.query('status', params.status, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<JobOfferListDto>>;
    })
  );
}

getAllJobOffers.PATH = '/rh/job-offers';
