/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CommissionMemberResponseDto } from '../../models/commission-member-response-dto';

export interface GetCommissionMembers$Params {
  commissionId: number;
}

export function getCommissionMembers(http: HttpClient, rootUrl: string, params: GetCommissionMembers$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CommissionMemberResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, getCommissionMembers.PATH, 'get');
  if (params) {
    rb.path('commissionId', params.commissionId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CommissionMemberResponseDto>>;
    })
  );
}

getCommissionMembers.PATH = '/rh/commissions/{commissionId}/members';
