/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CommissionMemberUserDto } from '../../models/commission-member-user-dto';

export interface GetAllCommissionMemberUsers$Params {
}

export function getAllCommissionMemberUsers(http: HttpClient, rootUrl: string, params?: GetAllCommissionMemberUsers$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CommissionMemberUserDto>>> {
  const rb = new RequestBuilder(rootUrl, getAllCommissionMemberUsers.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CommissionMemberUserDto>>;
    })
  );
}

getAllCommissionMemberUsers.PATH = '/rh/commissions/get_all_commissions_members';
