/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CommissionListDto } from '../../models/commission-list-dto';

export interface GetAllCommissions$Params {
  status?: 'ACTIVE' | 'CLOSED' | 'ARCHIVED';
}

export function getAllCommissions(http: HttpClient, rootUrl: string, params?: GetAllCommissions$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CommissionListDto>>> {
  const rb = new RequestBuilder(rootUrl, getAllCommissions.PATH, 'get');
  if (params) {
    rb.query('status', params.status, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CommissionListDto>>;
    })
  );
}

getAllCommissions.PATH = '/rh/commissions';
